version: "3.9"
services:
  dbo:
    image: zharfan21/dbo
    restart: always
    container_name: dbo
    ports:
      - 8181:8181
    depends_on:
      - postgres-db
    networks:
      - my-network

  postgres-db:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge